before_build:
  - nuget restore

build:
  verbosity: normal
  project: Sprung\Sprung.csproj

artifacts:

  - path: 'Sprung\bin\Debug\*.exe'
    name: 'Sprung'

  - path: 'SprungSetup\Debug\setup.exe'
    name: 'SprungSetup'
    
#after_build:
#  - cmd: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\devenv.exe" SprungSetup\SprungSetup.vdproj /Build Debug /Projectconfig Release'
